-keep class org.xmlpull.v1.** { *; }
-keepattributes Signature, *Annotation*, InnerClasses, EnclosingMethod

-keep class com.google.firebase.database.obfuscated.**{ *;}
-dontwarn org.ejml.**
-dontwarn org.xmlpull.**
-dontwarn io.reactivex.**
-dontwarn com.squareup.okhttp.**
-dontwarn com.thoughtworks.xstream.**
-dontwarn boofcv.**
-dontwarn java.awt.**
